[build]
  functions = "functions"

[[redirects]]
  from = "/web-stories/*"
  to = "https://web-stories.whisperofyum.com/web-stories/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}